name: Build and Deploy to Azure Web App for Containers

on:
  push:
    branches: [ "main" ]
    paths:
      - "go-gin-api/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "go-gin-api/**"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./go-gin-api

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Azure Container Registry (ACR)
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_NAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    # Step 4: Build and push the Docker image to ACR
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/go-gin-api:${{ github.sha }} .
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/go-gin-api:${{ github.sha }}

    # Step 5: Deploy the image to Azure Web App for Containers
    - name: Deploy to Azure Web App
      run: |
        az webapp config container set \
          --name ${{ secrets.WEBAPP_NAME }} \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --docker-custom-image-name ${{ secrets.ACR_NAME }}.azurecr.io/go-gin-api:${{ github.sha }} \
          --docker-registry-server-url https://${{ secrets.ACR_NAME }}.azurecr.io