name: Build and Deploy Go API

on:
  push:
    branches: [ "main" ]
    paths:
      - "go-gin-api/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "go-gin-api/**"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./go-gin-api

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        
    - name: Install dependencies and build
      run: |
        go mod tidy
        GOOS=windows GOARCH=amd64 go build -o bin/app.exe ./cmd

    - name: Archive the built application
      run: tar -czf gin-api.tar.gz bin/

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: gobipul
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ github.workspace }}/go-gin-api/gin-api.tar.gz
