# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
    paths:
      - "go-gin-api/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "go-gin-api/**"
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build Go application
      run: |
        go build -o gin-api

    - name: Archive the built Go application
      run: |
        tar -czf gin-api.tar.gz gin-api

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: gobipul
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: gin-api.tar.gz