# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
    paths:
      - "go-gin-api/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "go-gin-api/**"
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build for Windows
      run: |
        GOOS=windows GOARCH=amd64 go build -v -o go-gin-api.exe ./...
      working-directory: go-gin-api

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: gobipul.azurewebsites.net
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./go-gin-api/go-gin-api.exe
